apiVersion: batch/v1
kind: Job
metadata:
  name: {job_name}
  labels:
    app: ml-training-job
spec:
  ttlSecondsAfterFinished: 60 # delete job after finished
  template:
    spec:
      containers:
      - name: ml-training
        image: {image_name}
        env:
{dynamic_env_vars}
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 4
